version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - db
    networks:
      - ecommerce
  
  app:
    build: docker/php-fpm
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      # - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    restart: always
    depends_on:
      - db
    networks:
      - ecommerce

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      # MYSQL_USER: root  # already root user name - new definition cause error
      MYSQL_PASSWORD: root
    volumes:
      # - ./docker/mariadb/backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - ./docker/mariadb/data:/var/lib/mysql
      # - ./docker/mariadb:/var/lib/mariadb/data
    restart: always
    ports:
      - "3306:3306"
    networks:
      - ecommerce

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    # links:
    #   - db
    ports:
      - "8080:80" 
    networks:
      - ecommerce
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - /sessions
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    restart: always

networks:
  ecommerce:
    driver: bridge